import { createTRPCNext } from "@trpc/next";
import { AppRouter } from "~/server/routers/_app";
import superjson from "superjson";
import { httpBatchLink } from "@trpc/client";
import type { GetInferenceHelpers } from "@trpc/server";
function getBaseUrl() {
  if (typeof window !== "undefined") {
    return "";
  }
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}`;
  }

  return `http://localhost:${process.env.PORT ?? 3000}`;
}

export const trpc = createTRPCNext<AppRouter>({
  config() {
    return {
      transformer: superjson,
      links: [
        httpBatchLink({
          url: `${getBaseUrl()}/api/trpc`,
        }),
      ],
    };
  },
  ssr: false,
});

// Helper type for inferring input types and output types generated by your @trpc/server router.
export type InferProcedures = GetInferenceHelpers<AppRouter>;
